############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Resources"
url = "/resources"
weight = 3

[[main]]
weight = 4
name = "Events"

[[main]]
parent = "Events"
name = "Upcoming Events"
url = "/events"

[[main]]
parent = "Events"
name = "NCB Week"
url = "/ncb-week"

[[main]]
parent = "Events"
name = "Past Events"
url = "/past-events"

[[main]]
weight = 5
name = "Team"

[[main]]
parent = "Team"
name = "Core Members"
url = "/core"

[[main]]
parent = "Team"
name = "NCB Board"
url = "/advisors"

[[main]]
name = "Partnerships"
url = "/partnerships"
weight = 6

[[main]]
name = "Jobs"
url = "/jobs"
weight = 7

[[main]]
name = "Contact"
url = "/contact"
weight = 8

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
