############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Resources"
url = "/resources"
weight = 3

[[main]]
weight = 4
name = "Events"

[[main]]
parent = "Events"
name = "NCB Week"
url = "/ncb-week"

[[main]]
weight = 5
name = "Team"

[[main]]
parent = "Team"
name = "Core Members"
url = "/core-members"

[[main]]
parent = "Team"
name = "Advisors"
url = "/advisors"

[[main]]
name = "Blog"
url = "/blog"
weight = 6

[[main]]
name = "Contact"
url = "/contact"
weight = 7

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
